defmodule AgendaWeb.Components.MeetForm do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.LiveComponent
  alias Surface.Components.Form
  alias Surface.Components.Form.{Field, TextInput, Label, Select, TextArea}
  alias Agenda.Schedule
  alias Agenda.Schedule.Meeting

  # use Surface.Components
  # data changeset, :any, default:  Schedule.change_meeting(%Meeting{})
  def render(assigns) do
    ~F"""
    <Form for={Schedule.change_meeting(%Meeting{})} action="/meetings">
      <Field name={:title}>
        <Label class="label" />
        <div class="control">
          <TextInput value="title" class="input is-info" />
        </div>
      </Field>
      <Field name={:description}>
        <Label class="label" />
        <div class="control">
          <TextArea class="textarea is-info" rows="4" opts={placeholder: "4 lines of textarea"} />
        </div>
      </Field>
      <Field name={:week}>
        <Label class="label" />
        <div class="select">
          <Select options={First: "first", Second: "second", Third: "third", fourth: "fourth", fifth: "fifth"} />
        </div>
      </Field>
      <Field name={:day}>
        <Label class="label" />
        <div class="select">
          <Select options={
            monday: "monday",
            tuesday: "tuesday",
            wednesday: "thursday",
            friday: "friday",
            saturday: "saturday",
            sunday: "sunday"
          } />
        </div>
      </Field>
      <Field name={:month}>
        <Label class="label" />
        <div class="select">
          <Select options={
            january: "january",
            february: "february",
            march: "march",
            april: "april",
            may: "may",
            june: "june",
            july: "july",
            august: "august",
            september: "september",
            october: "october",
            november: "november",
            december: "december"
          } />
        </div>
      </Field>
      <Field name={:year}>
        <Label class="label" />
        <div class="select">
          <Select options={"2022": "2022", "2023": "2023", "2024": "2024", "2025": "2025", "2026": "2026"} />
        </div>
      </Field>
      <div>
        <button class="button is-link" type="submit">Submit</button>
      </div>
    </Form>
    """
  end
end
